name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

#     - name: Test
#       run: go test -v ./...
      
    - name: Build linux amd64
      run: GOOS=linux GOARCH=amd64 go build -o ./http-debug-server_linux-amd64 http-debug-server

    - name: Build darwin amd64
      run: GOOS=darwin GOARCH=amd64 go build -o ./http-debug-server_darwin-amd64 http-debug-server

    - name: Build darwin arm64
      run: GOOS=darwin GOARCH=arm64 go build -o ./http-debug-server_darwin-arm64 http-debug-server

    - name: Upload http-debug-server_linux-amd64
      uses: actions/upload-artifact@v2.2.4
      with:
        name: http-debug-server_linux-amd64
        path: ./http-debug-server_linux-amd64
    
    - name: Upload http-debug-server_darwin-amd64
      uses: actions/upload-artifact@v2.2.4
      with:
        name: http-debug-server_darwin-amd64
        path: ./http-debug-server_darwin-amd64
        
        
    - name: Upload http-debug-server_darwin-arm64
      uses: actions/upload-artifact@v2.2.4
      with:
        name: http-debug-server_darwin-arm64
        path: ./http-debug-server_darwin-arm64
